<?php
namespace SAR\tests\lib;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-28 at 11:30:50.
 */
class CoreTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers SAR\lib\Core::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
